language: java

jdk:
  - openjdk8

script:
  #  - mvn test jacoco:report
  - mvn clean test-compile -pl core -am
  - ls core/target/classes/ji/core

#after_success:
#  - mvn coveralls:report

notifications:
  email:
    - zhong.lunfu@gmail.com