version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: maven:3.6-jdk-8-alpine
    steps:
      - checkout
      - run: mvn clean test jacoco:report
      - run: mvn coveralls:report -DrepoToken=$COVERALL
      - run: mvn sonar:sonar -Dsonar.projectKey=jiboard_ji  -Dsonar.organization=jiboard -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login=${SONAR_TOKEN}
