version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: maven:3.6-jdk-8-alpine
    steps:
      - checkout
      - run: mvn clean test-compile -pl core -am
      - run: ls core/target/classes/ji/core
#      - run: mvn clean test jacoco:report
#      - run: mvn coveralls:report -DrepoToken=$COVERALL